Feature/analytics 2.0 documentation
ZupIT/docs-beagle pull request #290
Opened 2021-02-11 16:18 UTC by hectorcustodiozup

New Session added - Analytics 2.0

2021-02-26 14:59 UTC, luismaximozup requested changes
wait

2021-03-09 13:49 UTC, luismaximozup submitted a review, later dismissed

2021-03-09 17:09 UTC, luisoliveirazup approved these changes

2021-03-09 18:17 UTC, vitorbassozup commented
missing portuguese version

2021-03-11 18:04 UTC, carlossteinzup approved these changes

2021-03-11 18:04 UTC, merged