feat: adding BeagleView states to iOS doc
ZupIT/docs-beagle pull request #314
Opened 2021-02-17 17:54 UTC by gabcoelho

## Description

**Beagle version 1.6.0**

This PR adds the documentation to using states in iOS's BeagleView, it provides the user a way to configure BeagleView's state, it is something that we didn't have in iOS before.

2021-02-26 14:59 UTC, luismaximozup requested changes
wait

2021-03-01 19:17 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +**ScreenType.Remote:** Receives an URL with a server-driven component. This inicialization allows you to configure BeagleView's states through `beagleViewStateObserver` parameter.
This initialization

2021-03-01 19:17 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +**ScreenType:** It's a enum that allows you to initialize BeagleView in three ways:
It's an enum

2021-03-01 19:17 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +* `Remote:` Receives an URL with a server-driven component. If there was an error when loading your server-driven screen, an optional fallback view can be configured, which would be a screen build on
If there is an error ...

2021-03-01 19:17 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Below is a native layout that will be used to exemplify the use of `AutoLayout` together with Beagle:
Check out below, a native layout ...

2021-03-01 19:17 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Now, inside `BeagleViewViewController` class, three native `UILabel` texts will be created and positioned with `AutoLayout`, as can be seen in the `setupLabels` function.
Now, inside `BeagleViewViewController` class, three native `UILabel` texts will be created and positioned with `AutoLayout`, **as you can see in the** .....

2021-03-01 19:17 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Below are two examples of how to instantiate a `BeagleView`, one starting with a **declarative** Beagle component and the other in **remote** mode with a server-driven component.
See below two examples on how to instantiate a `BeagleView`, one starting with a **declarative** Beagle component and the other in a **remote** mode with a server-driven component.

2021-03-01 19:17 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Below is an example where a BeagleView was created that receives BeagleView's states to be able to treat them.
Check out below an example where a BeagleView was created and it receives BeagleView's states to treat them.

2021-03-01 19:17 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Bellow is the complete example of `BeagleViewViewController` class.
You can see a complete `BeagleViewViewController` class example below:

2021-03-01 19:17 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/beagle-view.md
> +**ScreenType.Remote:** Na inicialização de uma view remota recebe-se a URL da sua tela ou componente server-driven. A configuração dos estados da beagle view também pode ser feita através do parâmetr
**ScreenType.Remote:** Na inicialização de uma View remota, ela recebe a URL da sua tela ou componente server-driven. A configuração dos estados da Beagle View também pode ser feita por meio do parâmetro `beagleViewStateObserver`.

2021-03-01 19:17 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/beagle-view.md
> +Agora, você irá criar três textos nativos do tipo `UILabel` e irá posicioná-los com o `AutoLayout`, como na função `setupLabels` abaixo.
Agora, você irá criar três textos nativos do tipo `UILabel` e irá posicioná-los com o `AutoLayout`, como na função `setupLabels` abaixo:

2021-03-01 19:17 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/beagle-view.md
Veja abaixo dois exemplos de instanciação de uma `BeagleView`, uma inicializada no modo **declarative** e outro no modo **Remote**:

2021-03-01 19:17 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/beagle-view.md
> +Abaixo temos um exemplo onde foi criada uma BeagleView que recebe os estados para poder tratá-los.
Veja abaixo um exemplo, onde uma BeagleView foi criada e recebe os estados para poder tratá-los.

2021-03-01 19:17 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/beagle-view.md
> +Segue em exemplo a classe `BeagleViewViewController`completa.
Abaixo um exemplo da classe `BeagleViewViewController` completa.

2021-03-09 13:53 UTC, luismaximozup submitted a review, later dismissed

2021-03-09 15:15 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Check out below, a native layout that will be used to exemplify the use of `AutoLayout` together with Beagle:
```suggestion
Check out below a native layout to exemplify the use of `AutoLayout` together with Beagle:
```

2021-03-09 15:15 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Check out below an example where a BeagleView was created and it receives BeagleView's states to treat them.
```suggestion
You can see the states and deal with the `beagleViewStateObserver` parameter errors at the BeagleView startup with the `ScreenType.Remote` type.

Check out an example where a BeagleView was created and it receives BeagleView's states to treat them.
```

2021-03-09 15:15 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +You can see a complete `BeagleViewViewController` class example below:
```suggestion
You can see a `BeagleViewViewController` class example below:
```

2021-03-09 15:15 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/beagle-view.md
> +Crie uma classe do tipo `UIViewController` como descrito abaixo.
```suggestion
Crie uma classe do tipo `UIViewController`, como descrito abaixo: 
```

2021-03-09 15:15 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/beagle-view.md
> +Agora, você irá criar três textos nativos do tipo `UILabel` e irá posicioná-los com o `AutoLayout`, como na função `setupLabels` abaixo:
```suggestion
Agora, crie três textos nativos do tipo `UILabel` e posicione-os com o `AutoLayout`, como na função `setupLabels` abaixo:
```

2021-03-09 15:15 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/beagle-view.md
> +Veja abaixo um exemplo, onde uma BeagleView foi criada e recebe os estados para poder tratá-los.
```suggestion
Veja abaixo um exemplo de uma BeagleView que recebe os estados para poder tratá-los: 
```

2021-03-09 15:47 UTC, gabcoelho commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Check out below an example where a BeagleView was created and it receives BeagleView's states to treat them.
Acredito que mudou um pouco o significado e ficou confuso, mas com base na sua sugestão, o que você acha dessa forma: 

`You can observe BeagleViews's states and deal with errors through the `beagleViewStateObserver` parameter at BeagleView startup with the `ScreenType.Remote` type.
`

2021-03-09 17:27 UTC, vitorbassozup commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Pronto, você já pode usar a `BeagleView`.
Shouldn't this be in english?

2021-03-09 17:27 UTC, vitorbassozup commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +**ScreenType.Remote:** Receives an URL with a server-driven component. This initialization allows you to configure BeagleView's states through `beagleViewStateObserver` parameter.
```suggestion
**ScreenType.Remote:** Receives a URL with a server-driven component. This initialization allows you to configure BeagleView's states through `beagleViewStateObserver` parameter.
```

2021-03-09 17:27 UTC, vitorbassozup commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +* `Remote:` Receives an URL with a server-driven component. If there is an error when loading your server-driven screen, an optional fallback view can be configured, which would be a screen build on
```suggestion
* `Remote:` Receives a URL with a server-driven component. If there is an error when loading your server-driven screen, an optional fallback view can be configured, which would be a screen built on the frontend.
```

2021-03-09 17:35 UTC, gabcoelho commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Pronto, você já pode usar a `BeagleView`.
yep 😅 I was gonna commit that in the next commit

2021-03-09 20:10 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-ios/beagle-view.md
> +Check out below an example where a BeagleView was created and it receives BeagleView's states to treat them.
-- ótimoo, agora entendi o sentido ;)

2021-03-10 12:29 UTC, dantes-git approved these changes

2021-03-10 12:38 UTC, merged