feat: updates simple form and text input
ZupIT/docs-beagle pull request #335
Opened 2021-02-23 11:57 UTC by gabcoelho

## Description

**Beagle version 1.6.0**

This PR updates the documentation, adding new validation attributes for simple form and text input.

2021-02-26 14:58 UTC, luismaximozup requested changes
wait

2021-03-01 19:01 UTC, mdcpmoreira reviewed
Review done :)

2021-03-01 19:01 UTC, mdcpmoreira commented on content/pt/api/components/forms/simple-form.md
> +Ao clicar nesse botão, o onSubmit é ativado e a lista de ações será executada. É essa lista de ações que definirá o que deve acontecer com as informações so formulario, se serão enviadas para um back
```suggestion
Ao clicar nesse botão, o onSubmit é ativado e a lista de ações será executada. Essa lista de ações define o que deve acontecer com as informações do formulario: por exemplo, se elas serão enviadas para um backend \(através da ação [**sendRequest**]({{< ref path="/api/actions/sendrequest" lang="pt" >}})\), etc.
```

2021-03-01 19:01 UTC, mdcpmoreira commented on content/pt/api/components/forms/simple-form.md
> +Ao clicar nesse botão, o onSubmit é ativado e a lista de ações será executada. É essa lista de ações que definirá o que deve acontecer com as informações so formulario, se serão enviadas para um back
Aqui, fiquei na dúvida se devemos listar outras ações que essa lista define. Caso tenha, podemos reescrever essa parte para incluir.

2021-03-01 19:01 UTC, mdcpmoreira commented on content/pt/api/components/forms/simple-form.md
> +É uma ação do SimpleForm que executa uma lista de ações que são chamadas quando um formuário é submetido e inválido. Essa validação é realizada no componente `TextInput` a partir dos atributos **erro
```suggestion
É uma ação do SimpleForm que executa uma lista de ações que são chamadas **quando um formuário inválido é submetido**. Essa validação é realizada no componente `TextInput` a partir dos atributos **error** e **showError**.
```

2021-03-09 12:55 UTC, gabcoelho commented on content/pt/api/components/forms/simple-form.md
> +Ao clicar nesse botão, o onSubmit é ativado e a lista de ações será executada. É essa lista de ações que definirá o que deve acontecer com as informações so formulario, se serão enviadas para um back
Acredito que não seja necessário não, é mais um exemplo mesmo 😁

2021-03-09 13:53 UTC, luismaximozup approved these changes

2021-03-09 17:29 UTC, vitorbassozup approved these changes

2021-03-10 12:31 UTC, dantes-git approved these changes

2021-03-10 12:38 UTC, merged